// This file is auto-generated by @hey-api/openapi-ts

import * as Schemas from "./effect-schema.gen"
import * as Context from "effect/Context"
import * as Effect from "effect/Effect"
import * as Layer from "effect/Layer"
import * as Schema from "effect/Schema"
import type * as HttpClient from "effect/unstable/http/HttpClient"
import * as HttpApi from "effect/unstable/httpapi/HttpApi"
import * as HttpApiClient from "effect/unstable/httpapi/HttpApiClient"
import * as HttpApiEndpoint from "effect/unstable/httpapi/HttpApiEndpoint"
import * as HttpApiGroup from "effect/unstable/httpapi/HttpApiGroup"
import * as HttpApiSchema from "effect/unstable/httpapi/HttpApiSchema"

const BadRequest = Schemas.ErrorInfoSchema.pipe(HttpApiSchema.status(400))

const Forbidden = Schemas.ErrorInfoSchema.pipe(HttpApiSchema.status(403))

const RequestTimeout = Schemas.ErrorInfoSchema.pipe(HttpApiSchema.status(408))

const NotFound = Schemas.ErrorInfoSchema.pipe(HttpApiSchema.status(404))

const Conflict = Schemas.ErrorInfoSchema.pipe(HttpApiSchema.status(409))

const BasinsGroup = HttpApiGroup.make("basins").add(HttpApiEndpoint.get("listBasins", "/basins", {
  query: {
    prefix: Schema.optionalKey(Schema.String),
    start_after: Schema.optionalKey(Schema.String),
    limit: Schema.optionalKey(Schema.Number)
  },
  success: Schemas.ListBasinsResponseSchema.pipe(HttpApiSchema.status(200)),
  error: [
    BadRequest,
    Forbidden,
    RequestTimeout
  ]
}))

const RecordsGroup = HttpApiGroup.make("records").add(
  HttpApiEndpoint.get("read", "/streams/:stream/records", {
    params: { stream: Schemas.StreamNameStrSchema },
    query: {
      seq_num: Schema.optionalKey(Schemas.U64Schema),
      timestamp: Schema.optionalKey(Schemas.U64Schema),
      tail_offset: Schema.optionalKey(Schema.Number),
      clamp: Schema.optionalKey(Schema.Boolean),
      count: Schema.optionalKey(Schema.Number),
      bytes: Schema.optionalKey(Schema.Number),
      until: Schema.optionalKey(Schemas.U64Schema),
      wait: Schema.optionalKey(Schema.Number)
    },
    headers: {
      "s2-format": Schema.optionalKey(Schemas.FormatSchema),
      "s2-encryption-key": Schema.optionalKey(Schema.String)
    },
    success: [
      Schemas.ReadBatchSchema.pipe(HttpApiSchema.status(200)),
      HttpApiSchema.StreamSse({
        events: Schema.Union([
          Schema.Struct({
            data: Schema.fromJsonString(Schemas.ReadBatchSchema),
            event: Schema.Literals(["batch"]),
            id: Schema.String
          }),
          Schema.Struct({ data: Schema.String, event: Schema.Literals(["error"]) }),
          Schema.Struct({ data: Schema.fromJsonString(Schemas.PingEventDataSchema), event: Schema.Literals(["ping"]) })
        ])
      })
    ],
    error: [
      BadRequest,
      Forbidden,
      NotFound,
      RequestTimeout,
      Conflict,
      Schemas.TailResponseSchema.pipe(HttpApiSchema.status(416))
    ]
  }),
  HttpApiEndpoint.post("append", "/streams/:stream/records", {
    params: { stream: Schemas.StreamNameStrSchema },
    headers: {
      "s2-format": Schema.optionalKey(Schemas.FormatSchema),
      "s2-encryption-key": Schema.optionalKey(Schema.String)
    },
    payload: Schemas.AppendInputSchema,
    success: Schemas.AppendAckSchema.pipe(HttpApiSchema.status(200)),
    error: [
      BadRequest,
      Forbidden,
      NotFound,
      RequestTimeout,
      Conflict,
      Schemas.AppendConditionFailedSchema.pipe(HttpApiSchema.status(412))
    ]
  }),
  HttpApiEndpoint.get("checkTail", "/streams/:stream/records/tail", {
    params: { stream: Schemas.StreamNameStrSchema },
    success: Schemas.TailResponseSchema.pipe(HttpApiSchema.status(200)),
    error: [
      BadRequest,
      Forbidden,
      NotFound,
      RequestTimeout,
      Conflict
    ]
  })
)

export const S2Api = HttpApi.make("S2Api").add(BasinsGroup, RecordsGroup)

export type S2ProtocolClientApi = HttpApiClient.ForApi<typeof S2Api>

export type S2ProtocolClientOptions = {
  readonly baseUrl?: URL | string
  readonly transformClient?: (client: HttpClient.HttpClient) => HttpClient.HttpClient
  readonly transformResponse?: (
    effect: Effect.Effect<unknown, unknown, unknown>
  ) => Effect.Effect<unknown, unknown, unknown>
}

export const S2ProtocolClient = Context.Service<S2ProtocolClientApi>("effect-s2/S2ProtocolClient")

export const make = Effect.fn("S2ProtocolClient.make")((options?: S2ProtocolClientOptions) =>
  HttpApiClient.make(S2Api, options)
)

export const layer = (options?: S2ProtocolClientOptions) => Layer.effect(S2ProtocolClient, make(options))
