// This file is auto-generated by @hey-api/openapi-ts

import * as Schema from "effect/Schema"
import * as SchemaGetter from "effect/SchemaGetter"

export const AppendAckSchema = Schema.Struct({
  end: Schema.suspend(() => StreamPositionSchema),
  start: Schema.suspend(() => StreamPositionSchema),
  tail: Schema.suspend(() => StreamPositionSchema)
})

export const AppendConditionFailedSchema = Schema.Union([
  Schema.Struct({ fencing_token_mismatch: Schema.suspend(() => FencingTokenSchema) }),
  Schema.Struct({ seq_num_mismatch: Schema.suspend(() => U64Schema) })
])

export const AppendInputSchema = Schema.Struct({
  fencing_token: Schema.optionalKey(Schema.Union([Schema.Null, Schema.suspend(() => FencingTokenSchema)])),
  match_seq_num: Schema.optionalKey(Schema.Union([Schema.Null, Schema.suspend(() => U64Schema)])),
  records: Schema.Array(Schema.suspend(() => AppendRecordSchema))
})

export const AppendRecordSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.String),
  headers: Schema.optionalKey(Schema.Array(Schema.suspend(() => HeaderSchema))),
  timestamp: Schema.optionalKey(Schema.Union([Schema.Null, Schema.suspend(() => U64Schema)]))
})

export const BasinInfoSchema = Schema.Struct({
  created_at: Schema.DateFromString,
  deleted_at: Schema.optionalKey(Schema.Union([Schema.DateFromString, Schema.Null])),
  location: Schema.optionalKey(Schema.Union([Schema.Null, Schema.suspend(() => LocationNameSchema)])),
  name: Schema.suspend(() => BasinNameStrSchema)
})

export const BasinNameStrSchema = Schema.String.check(Schema.isMinLength(8), Schema.isMaxLength(48))

export const ErrorInfoSchema = Schema.Struct({ code: Schema.String, message: Schema.String })

export const FencingTokenSchema = Schema.String.check(Schema.isMaxLength(36))

export const FormatSchema = Schema.Literals(["raw", "base64"])

export const HeaderSchema = Schema.Tuple([Schema.String, Schema.String])

export const ListBasinsResponseSchema = Schema.Struct({
  basins: Schema.Array(Schema.suspend(() => BasinInfoSchema)),
  has_more: Schema.Boolean
})

export const LocationNameSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(64))

export const PingEventDataSchema = Schema.Struct({
  timestamp: Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)).pipe(
    Schema.decodeTo(
      Schema.BigInt.check(
        Schema.isGreaterThanOrEqualToBigInt(BigInt(0)),
        Schema.isLessThanOrEqualToBigInt(BigInt(Number.MAX_SAFE_INTEGER))
      ),
      {
        decode: SchemaGetter.transform((value) => BigInt(value)),
        encode: SchemaGetter.transform((value) => Number(value))
      }
    )
  )
})

export const ReadBatchSchema = Schema.Struct({
  records: Schema.Array(Schema.suspend(() => SequencedRecordSchema)),
  tail: Schema.optionalKey(Schema.Union([Schema.Null, Schema.suspend(() => StreamPositionSchema)]))
})

export const ReadEventSchema = Schema.Union([
  Schema.Struct({
    data: Schema.suspend(() => ReadBatchSchema),
    event: Schema.Literals(["batch"]),
    id: Schema.String.check(Schema.isPattern(RegExp("^[0-9]+,[0-9]+,[0-9]+$")))
  }),
  Schema.Struct({ data: Schema.String, event: Schema.Literals(["error"]) }),
  Schema.Struct({ data: Schema.suspend(() => PingEventDataSchema), event: Schema.Literals(["ping"]) })
])

export const SequencedRecordSchema = Schema.Struct({
  body: Schema.optionalKey(Schema.String),
  headers: Schema.optionalKey(Schema.Array(Schema.suspend(() => HeaderSchema))),
  seq_num: Schema.suspend(() => U64Schema),
  timestamp: Schema.suspend(() => U64Schema)
})

export const StreamNameStrSchema = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(512))

export const StreamPositionSchema = Schema.Struct({
  seq_num: Schema.suspend(() => U64Schema),
  timestamp: Schema.suspend(() => U64Schema)
})

export const TailResponseSchema = Schema.Struct({ tail: Schema.suspend(() => StreamPositionSchema) })

export const U64Schema = Schema.Number.check(Schema.isInt(), Schema.isGreaterThanOrEqualTo(0)).pipe(
  Schema.decodeTo(
    Schema.BigInt.check(
      Schema.isGreaterThanOrEqualToBigInt(BigInt(0)),
      Schema.isLessThanOrEqualToBigInt(BigInt(Number.MAX_SAFE_INTEGER))
    ),
    {
      decode: SchemaGetter.transform((value) => BigInt(value)),
      encode: SchemaGetter.transform((value) => Number(value))
    }
  )
)
